// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARkmToI3D9VbLijdMQcbalAWHOm253XL8',
    appId: '1:319083477759:web:2528cb58e8cb3e3729aaca',
    messagingSenderId: '319083477759',
    projectId: 'tap-card-app-75c37',
    authDomain: 'tap-card-app-75c37.firebaseapp.com',
    storageBucket: 'tap-card-app-75c37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD814d7qbqzeAlMTIgMSIzWiWnidBLJt60',
    appId: '1:319083477759:android:376364b1e3056c3629aaca',
    messagingSenderId: '319083477759',
    projectId: 'tap-card-app-75c37',
    storageBucket: 'tap-card-app-75c37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcG9cQcFP9DCTYlnnzpd0qq5HcjlzaUBs',
    appId: '1:319083477759:ios:5a1d80784860322c29aaca',
    messagingSenderId: '319083477759',
    projectId: 'tap-card-app-75c37',
    storageBucket: 'tap-card-app-75c37.firebasestorage.app',
    iosBundleId: 'com.atlaslinq.app',
    iosClientId: '319083477759-66gtmk9jtroltg4jobaqi666jn1ii2cv.apps.googleusercontent.com',
    androidClientId: '319083477759-336agdfvd081tm5ivd7s1va9jnp9cu58.apps.googleusercontent.com',
  );
}
